foreground         #c3c5c8
background         #0f1823
background_opacity 1.0
cursor             #c3c5c8

active_tab_foreground     #0f1823
active_tab_background     #c3c5c8
inactive_tab_foreground   #c3c5c8
inactive_tab_background   #0f1823

active_border_color   #c3c5c8
inactive_border_color #0f1823
bell_border_color     #259E61

color0       #0f1823
color8       #5e6774
color1       #259E61
color9       #259E61
color2       #54B976
color10      #54B976
color3       #2CD172
color11      #2CD172
color4       #406E93
color12      #406E93
color5       #4EB892
color13      #4EB892
color6       #5CE88A
color14      #5CE88A
color7       #c3c5c8
color15      #c3c5c8
